FROM node:13.3.0 AS compile-image

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
RUN npm install
RUN npm install -g @angular/cli

COPY . ./

EXPOSE 5014

CMD ng serve --host 0.0.0.0 --port 5014

#CMD npm run dev