name: develop

on: [push]

jobs:
  deploy_to_development:
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy the docker image
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ 'mgbako-web' }}
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME